# Generated by Django 4.0.4 on 2022-04-23 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('search', models.BooleanField(default=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField(default=datetime.datetime(2022, 4, 23, 20, 43, 43, 272715, tzinfo=utc))),
                ('average_color', models.CharField(max_length=8)),
                ('std_color', models.CharField(max_length=8)),
                ('url', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colorsoftheworld.website')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=8)),
                ('search_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colorsoftheworld.searchresult')),
            ],
        ),
    ]
