"""
Django settings for colors project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
# from dotenv import load_dotenv
import uti

# https://stackoverflow.com/questions/40216311/reading-in-environment-variables-from-an-environment-file

# load_dotenv()
#
# SETTINGS_SECRET_KEY = os.getenv('SECRET_KEY')
# SETTINGS_ENGINE = os.getenv('ENGINE')
# SETTINGS_NAME =  os.getenv('NAME')
# SETTINGS_USER = os.getenv('USER')
# SETTINGS_PASSWORD = os.getenv('PASSWORD')
# SETTINGS_HOST = os.getenv('HOST')
# SETTINGS_PORT = os.getenv('PORT')
#









# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['colorsoftheworld-vpcuqkwkfq-ew.a.run.app', 'colorsoftheworld.diplabs.app', 'localhost']

# https://stackoverflow.com/questions/29573163/django-admin-login-suddenly-demanding-csrf-token
CSRF_TRUSTED_ORIGINS=['https://*.colorsoftheworld.diplabs.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorsoftheworld'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'colors.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'colors.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# https://stackoverflow.com/questions/42077532/django-security-and-settings

#  hELP!
DATABASES = {
    'default': {
        'ENGINE': uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_ENGINE'),
        'NAME': uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_NAME'),
        'USER': uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_USER'),
        'PASSWORD': uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_PASSWORD'),
        'HOST': uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_HOST'),
        'PORT': uti.access_secret_version('projects/125510501046/secrets/colorsoftheworld_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
